[project]
name = 'Blockchain-Based-Specialized-Hand-Blown-Glass-Authentication'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.artist-verification]
path = 'contracts/artist-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.studio-verification]
path = 'contracts/studio-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.technique-documentation]
path = 'contracts/technique-documentation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
